
BLENDER="A:\Blender\blender.exe"
DIST=../dist

all : \
    $(DIST)/myscene.pnct \
    $(DIST)/myscene.scene \

$(DIST)/myscene.scene : myscene.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "myscene.blend:Main" "$(DIST)/myscene.scene"

$(DIST)/myscene.pnct : myscene.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "myscene.blend:Main" "$(DIST)/myscene.pnct" 